/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ItRepositoriesLazyImport = createFileRoute('/it/repositories')()
const ItArticlesLazyImport = createFileRoute('/it/articles')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ItRepositoriesLazyRoute = ItRepositoriesLazyImport.update({
  path: '/it/repositories',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/it/repositories.lazy').then((d) => d.Route),
)

const ItArticlesLazyRoute = ItArticlesLazyImport.update({
  path: '/it/articles',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/it/articles.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/it/articles': {
      id: '/it/articles'
      path: '/it/articles'
      fullPath: '/it/articles'
      preLoaderRoute: typeof ItArticlesLazyImport
      parentRoute: typeof rootRoute
    }
    '/it/repositories': {
      id: '/it/repositories'
      path: '/it/repositories'
      fullPath: '/it/repositories'
      preLoaderRoute: typeof ItRepositoriesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  ItArticlesLazyRoute,
  ItRepositoriesLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/it/articles",
        "/it/repositories"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/it/articles": {
      "filePath": "it/articles.lazy.tsx"
    },
    "/it/repositories": {
      "filePath": "it/repositories.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
